server:
  port: 8080

spring:
  server:
    servlet:
      encoding:
        charset: UTF-8
        enabled: true
        force: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:100MB}
      max-request-size: ${MAX_REQUEST_SIZE:100MB}
jwt:
  secret: MinhaChaveSuperSecretaParaJWT123
  expiration: 86400000
